### ISSUE TITLE
Verify order of method invocations

### ISSUE THREAD

**Issue by florieger** [jonreid/OCMockito#103]
As far as I can see, there is no way to verify the order of method invocations on a mock.
Or am I missing something?

**Comment by florieger** [comment]
Could be solved by the given

**Comment by florieger** [comment]
Could be solved by 

https://github.com/jonreid/OCMockito/pull/93

**Comment by florieger** [comment]
I think I found a solution based on this pull request:
https://github.com/jonreid/OCMockito/pull/93

Description of the solution:
http://stackoverflow.com/questions/29745716/ocmockito-verify-order-of-method-invocations

**Comment by jonreid** [comment]
This goes back to issue #18. Mockito functionality is coming to OCMockito slowly, piece by piece…
