### ISSUE TITLE
given only works for ObjC methods

### ISSUE THREAD

**Issue by tomaz** [jonreid/OCMockito#11]
Default implementation doesn't work in Cedar due to using `self` in `given` macro definition. Cedar uses plain C functions, so `self` isn't available. To compensate, I use this macro:

```
#ifdef given
#	undef given
#	define given(methodCall) MKTGivenWithLocation([SpecHelper specHelper], __FILE__, __LINE__, methodCall)
#endif
```

Would be nice to support plain C style of unit tests as well.

**Comment by tomaz** [comment]
Thanks. No rush for that, at least for me - I since reverted to XCTest.

**Comment by jonreid** [comment]
It looks like Cedar has changed? Closing, feel free to reopen if it's still an issue.
