### ISSUE TITLE
`given([... anything()])` does not work for `NSError **` arguments

### ISSUE THREAD

**Issue by tikitu** [jonreid/OCMockito#111]
The following code does not compile, because the `anything()` apparently cannot match an `NSError **` parameter:

    id aMock = mock([NSFetchedResultsController class]);
    [given([aMock performFetch:anything()]) willReturnBool:YES];

The error reported is

    Implicit conversion of an Objective-C pointer to 'NSError *__autoreleasing *' is disallowed with ARC

Suggestions for alternative ways to achieve the same result would also be gratefully received! (I see changes from v1.2.0 to support `NSError **` but I didn't manage to understand how to apply them to `given()`, as opposed to `verify()`.)

**Comment by jonreid** [comment]
Try this:

    [[[given([aMock performFetch:NULL])] withMatcher:anything()] willReturnBool:YES];

**Comment by ayechanpyaesonework** [comment]
It works!!!! Thanks you.
