### ISSUE TITLE
retainCount issues when setting expectations on copy method.

### ISSUE THREAD

**Issue by cerihughes** [jonreid/OCMockito#113]
I've noticed a problem when my code under test uses the `copy` method on a mock. I can set up an expectation for the copy method and tell it to return the same instance, i.e.:
```
    [given([mockObject copy]) willReturn: mockObject];
```

but this then results in a mockObject that is over-released, and a crash when the test ends.

This can be reproduced as follows:

```
#import <XCTest/XCTest.h>

#define MOCKITO_SHORTHAND
#import <OCMockitoIOS/OCMockitoIOS.h>
#define HC_SHORTHAND
#import <OCHamcrestIOS/OCHamcrestIOS.h>

@interface CopyingClass : NSObject

@property (nonatomic, copy, readonly) NSURL *url;

- (instancetype)initWithURL:(NSURL *)url;

@end

@implementation CopyingClass

- (instancetype)initWithURL:(NSURL *)url
{
    if (!(self = [super init])) {
        return nil;
    }

    _url = [url copy];

    return self;
}

@end

@interface CopyingTest : XCTestCase

@end

@implementation CopyingTest

- (void)testCopying
{
    NSURL *mockUrl = mock([NSURL class]);

    CopyingClass *copyingClass = [[CopyingClass alloc] initWithURL:mockUrl];

    // This assert fails as the copy method in the code under test returns nil without an expectation set.
    assertThat(copyingClass.url, is(notNilValue()));

    stopMocking(mockUrl);
}

- (void)testCopyingWithCopyExpectation
{
    NSURL *mockUrl = mock([NSURL class]);

    [given([mockUrl copy]) willReturn:mockUrl];

    CopyingClass *copyingClass = [[CopyingClass alloc] initWithURL:mockUrl];

    assertThat(copyingClass.url, is(notNilValue()));

    stopMocking(mockUrl);

    // This test crashes with EXC_BAD_ACCESS as the mock is over-released.
}

- (void)testCopyingWithCopyExpectationAndRetain
{
    NSURL *mockUrl = mock([NSURL class]);

    [given([mockUrl copy]) willReturn:mockUrl];
    CFBridgingRetain(mockUrl);

    CopyingClass *copyingClass = [[CopyingClass alloc] initWithURL:mockUrl];

    assertThat(copyingClass.url, is(notNilValue()));

    stopMocking(mockUrl);

    // This test passes, but I don't want to be manually fiddling with the retainCount in a test.
}

@end
```

HTH. Please get in touch with any questions!

Ceri

**Comment by cerihughes** [comment]
This is using OCMockito from ref `56851e4`

**Comment by jonreid** [comment]
The issue doesn't seem to be about `copy` in particular, but around having a stubbed method return a mock. I've had another report of a similar situation involving mock1 returning mock2. You helped provide the workaround, `CFBridgingRetain(mock2)` — thank you.

But what do you suppose is going on?

**Comment by jonreid** [comment]
Correction: This is about `copy`. I've been able to have mocks returning mocks in other situations. When I take the crashing tests and substitute a different method, it all works.

**Comment by jonreid** [comment]
It's definitely a hackaround, but it works. Thanks!

**Comment by cerihughes** [comment]
I think there's more to do here. Basically, I think the problem is because of the "Basic Memory Management" rules defined at https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/MemoryMgmt/Articles/mmRules.html

Any method names starting with the prefixes `alloc`, `new`, `copy` and `mutableCopy` will cause the same problem.

I've put together a quick 'n' dirty change that shows the issue and proposes a fix: https://github.com/jonreid/OCMockito/pull/135

**Comment by cerihughes** [comment]
I think there's still some ambiguity around the rules defined in that page. Instance method names starting with `copy` and `mutableCopy` are easy to test, and I could easily reproduce the crash and show that the fix worked.

Method names starting with `new` and `alloc` are not so clear cut though. I don't know if these rules only cover static methods, or whether instance methods need to adhere to these rules to. I couldn't get test failures to occur for these cases.

I'll post a question on the Apple dev forums to see if I can get a bit more information about the rules.

HTH!

Ceri
