### ISSUE TITLE
Should decrement number of invocations after matching

### ISSUE THREAD

**Issue by gchaurais** [jonreid/OCMockito#114]
Suppose I have:

[myMock myMethod];
[verify(myMock) myMethod];
[myMock myMethod];
[verify(myMock) myMethod];

This is the most logical way to write this test. Every time the method myMethod gets called, I want to verify it's been called.

Unfortunately, that code fails. The reason is because verify(mock) is the same as calling verifyCount(mock, times(1)) and after a verification is done, the invocations that have already been successfully verified aren't removed from the list of recordedInvocations. In other words, in order to make my test pass, I'd need to change the second call to either:

[verifyCount(myMock, times(2)) myMethod];

or:

[verifyCount(myMock, atLeast(1)) myMethod];

The first option works, but it's not intuitive for people reading my test. All I want is to verify every time myMethod is called. Option two might not work because I might want to check using =, instead of >=.

One possibility to solve this problem is to change the numberOfMatchingInvocations method of the MKTVerificationData class to:

- (NSUInteger)numberOfMatchingInvocations
{
        NSUInteger count = 0;
        NSMutableArray *registeredInvocations = data.invocations.registeredInvocations;
        for (int i = registeredInvocations.count - 1; i >= 0; i--) {
            if ([data.wanted matches:registeredInvocations[i]]) {
                ++count;
                [registeredInvocations removeObjectAtIndex:i];
            }
        }
        return count;
}

I'm swizzling it in my code so I can have proper behavior, but I'd love to have the correct behavior by default.

**Comment by jonreid** [comment]
Done. Thankfully, my recent reworking of verification made it easy.
