### ISSUE TITLE
Race condition when stubbed method is called from multiple threads

### ISSUE THREAD

**Issue by brianvanderwal** [jonreid/OCMockito#117]
I'm getting an intermittent EXC_BAD_ACCESS when using a mock object simultaneously on different threads.  The actual exception occurs in `-[MKTInvocationContainer findAnswerFor:]` but I was able to work around the issue by modifying `-[MKTBaseMockObject forwardInvocation:]` as follows:

    - (void)forwardInvocation:(NSInvocation *)invocation
    {
        if (self.stoppedMocking)
            return;
        if ([self handlingVerifyOfInvocation:invocation])
            return;
        @synchronized (self) {
            [self prepareInvocationForStubbing:invocation];
            [self answerInvocation:invocation];
        }
    }

**Comment by jonreid** [comment]
Committed in d283eb20 -- thanks for the fix!
