### ISSUE TITLE
Architecture mismatch with OCHamcrest when building

### ISSUE THREAD

**Issue by weissazool** [jonreid/OCMockito#119]
For platforms other than iOS (OS X, tvOS, watchOS) building OCMockito results in the following error:

```
ld: building for OSX, but linking against dylib built for iOS, file '../Carthage/Build/iOS/OCHamcrest.framework/OCHamcrest' for architecture x86_64
```

I've experimented with making changes to the OCMockito project file to import the appropriate framework, but it still ends up grabbing the library built for iOS.

**Comment by weissazool** [comment]
Since Carthage's default is to build for all platforms, it will fail to build if you are using OCMockito via Carthage. 

If you're using iOS, it can be worked around by adding `--platform iOS` to any Carthage command. On any other platform, though, no luck.

**Comment by anagromataf** [comment]
@weissazool Just had the same issue. The project contains a framework search path, that is to general.
