### ISSUE TITLE
OCMockito build issues when manually importing it as a framework

### ISSUE THREAD

**Issue by ronak2121** [jonreid/OCMockito#120]
Hi,

We're manually importing OCMockito into our projects now. By manually importing, I mean, dragging the project file into the project and manually setting up the "Target Dependencies" and "Link Frameworks" steps.

When we do that and import OCMockito, we are getting the following build errors:

<module-includes>:1:1: Umbrella header for module 'OCMockito' does not include header 'MKTBaseMockObject.h'
<module-includes>:1:1: Umbrella header for module 'OCMockito' does not include header 'MKTClassObjectMock.h'
<module-includes>:1:1: Umbrella header for module 'OCMockito' does not include header 'MKTObjectAndProtocolMock.h'
<module-includes>:1:1: Umbrella header for module 'OCMockito' does not include header 'MKTObjectMock.h'
<module-includes>:1:1: Umbrella header for module 'OCMockito' does not include header 'MKTProtocolMock.h'

Is fixing this as simple as importing these files into the Umberella header? I imagine we aren't importing them into the Umberella header on purpose?

**Comment by jonreid** [comment]
Xcode is silly not to recognize transitive imports. Thanks for reporting this, try 3cc8b1f
