### ISSUE TITLE
verifyCount() don't works as expected with HCArgumentCaptor

### ISSUE THREAD

**Issue by leanid-raichonak** [jonreid/OCMockito#122]
Hi. I have next test case before updating to 3.0.1 (was 1.4.0 before):
```objective-c
[_cache userAppActivityWithPhoneNumbers:@[@"1"] completion:^(BOOL succed, NSDictionary *activities) {}];
    
HCArgumentCaptor *onlineCompletionCaptor = [HCArgumentCaptor new];
[verify(_phoneService) requestAppActivityInfoForNumbers:@[@"1"] withCompletion(id)onlineCompletionCaptor];
void (^completion)(BOOL result, NSDictionary *phoneNumberToAppIDMap) = [onlineCompletionCaptor value];
    
completion(YES, @{});
    
__block BOOL _succed = NO;
__block NSDictionary *_activities = nil;
[_cache userAppActivityWithPhoneNumbers:@[@"1"] completion:^(BOOL succed, NSDictionary *activities) {
    _succed = succed;
    _activities = activities;
}];
    
[verifyCount(_phoneService, times(1)) requestAppActivityInfoForNumbers:@[@"1"] withCompletion:anything()];
```
method `userAppActivityWithPhoneNumbers` from `_cache` object directly calls method `requestAppActivityInfoForNumbers` and `verifyCount` worked as expected before updating. But now ` verifyCount` fails (allegedly method was not called at all), although `requestAppActivityInfoForNumbers` definitely calls.

I saw what `verifyCount()` was changed in 3.0.0 and seems broken something.

**Comment by jonreid** [comment]
Under the old rules, verify (and verifyCount) continue to accumulate all counts. The new rules break backwards compatibility, which is indicated by the bump of the major version number to v3.

Under the new rules, when you verify a call, it will no longer consider it if you verify it a second time. So with your test, it looks like you verify once, and then again. A verifyCount of `times(1)` under the old rules means it was not called again after the first verify. To express this with the new rules, change `times(1)` to `never()`.
