### ISSUE TITLE
Argument captor capturing values twice

### ISSUE THREAD

**Issue by dflems** [jonreid/OCMockito#123]
Trivial example:

```objc
#import <XCTest/XCTest.h>
#import <OCMockitoIOS/OCMockitoIOS.h>
#import <OCHamcrestIOS/OCHamcrestIOS.h>

@interface VerifyCaptor : XCTestCase
@end

@implementation VerifyCaptor

- (void)testExample
{
    NSString *aMock = mock([NSString class]);
    [aMock stringByAppendingString:@"foo"];
    [aMock stringByAppendingString:@"bar"];
    
    HCArgumentCaptor *captor = [HCArgumentCaptor new];
    [verifyCount(aMock, times(2)) stringByAppendingString:(id)captor];
    
    NSLog(@"%@", captor.allValues);
}

@end
```

The given test passes but `allValues` contains `@[@"foo", @"bar", @"foo", @"bar"]` where it feels like it should just contain `@[@"foo", @"bar"]`. I assume this is because the captor is capturing on `matches:` which can be called from many places.

**Comment by jonreid** [comment]
Thank you for the example.

**Comment by jonreid** [comment]
You're quite correct: OCHamcrest makes no promises about how many times `matches:` will be called. That's why, in normal circumstances, matchers should be idempotent.

HCArgumentCaptor is an exception. I'm adding a `captureEnabled` property in the hope that it will give OCMockito finer control.

**Comment by jonreid** [comment]
Fixed! Thank you for reporting.

**Comment by werelord** [comment]
Is there any option when the mocked object being called is inserted into a class under test, and you don't necessarily have access to the `captureEnabled` property??
