### ISSUE TITLE
Verifying class method calling

### ISSUE THREAD

**Issue by carmelosui** [jonreid/OCMockito#127]
```
__strong Class classMock = mockClass([MyClass class]);
[MyClass myMethod];
[MKTVerifyCount(classMock, times(1)) myMethod];
```

I'm not sure if I'm doing it wrong or it has no such feature, I could not find a way to verify class method calling.

**Comment by igorsales** [comment]
You need to call [classMock myMethod] for it to work. However, have a look at my merge request which adds support for singletons, then I suspect your code could work after using stubSingleton().

**Comment by jonreid** [comment]
For now, though: Having created classMock, you need a way to inject it, just as you would an mock of an instance.

This is different from OCMock, which swizzles class methods.
