### ISSUE TITLE
Is it possible to stub a super class method which is overwritten in the sub class?

### ISSUE THREAD

**Issue by sarat-velumuri** [jonreid/OCMockito#130]
Is it possible to stub a super class method which is overwritten in the sub class?

Suppose I have a method in super class names classMethod, what I am looking for is:
A. Superclass implemented classMethod.
B. Subclass overrides classMethod and just has a code call [super classMethod].
C. Class mock made of Superclass.
D. classMethod stubbed on the class mock.

[Superclass classMethod] returns the stubbed value (As expected).
[Subclass classMethod] returns normal return value, but I want it to have it return the stubbed value.

**Comment by jonreid** [comment]
I'm afraid not. I think I see what you're trying to do: write a test that ensures correct calling of super. This can be done with some clever swizzling, as described in the book [Test-Driven iOS Development](http://www.amazon.com/gp/product/0321774183/ref=as_li_tl?ie=UTF8&camp=1789&creative=9325&creativeASIN=0321774183&linkCode=as2&tag=qualitycoding-20&linkId=KJILX4KVZM4GUHWY).

Calling super is one area I don't TDD.
