### ISSUE TITLE
Add Cocoapods support for stubSingleton

### ISSUE THREAD

**Issue by nakp** [jonreid/OCMockito#134]
Please, submit a new tag to make stubSingleton public for cocoapods.

That change is available since May 13th, and the last version was bumped on Jun 25th, but still wasn't merged until recently, and the docs show it as available

**Comment by jonreid** [comment]
…I'm nearly done cleaning up stubSingleton…

**Comment by nakp** [comment]
Oh, ok, I thought it was ready, I've been using it for a while and I have not had any issues. I'll wait then
