### ISSUE TITLE
Swift Static Declaration of 'times' follows non-static declaration

### ISSUE THREAD

**Issue by atacengiz** [jonreid/OCMockito#138]
I tried to add OCMockito and OCHamcrest to my Objective-c bridging header but i can not build the project because of Swift Static Declaration of 'times' follows non-static declaration error on OCMockito.h line 269 (I am using version 4.0.1) with XCode 8.0. What should i do to fix this error ?

**Comment by jonreid** [comment]
I'm surprised to find anyone trying to use OCMockito in Swift! I'm afraid your choices are either:
- `#define MKT_DISABLE_SHORT_SYNTAX` somewhere
- Comment out the offending line, knowing that you'll have to do this whenever you update OCMockito.
