### ISSUE TITLE
MKTArgumentCaptor to HCArgumentCaptor migration

### ISSUE THREAD

**Issue by saiday** [jonreid/OCMockito#146]
I have used `MKTArgumentCaptor` as my argument captor, on updating `OCMockito` seems like now there's new `HCArgumentCaptor` instead of old `MKTArgumentCaptor`.

In some use cases, I used to capture completion block and execute it to solve async testing issue.

```objective-c
    MKTArgumentCaptor *successCaptor = [[MKTArgumentCaptor alloc] init];
    MKTArgumentCaptor *failCaptor = [[MKTArgumentCaptor alloc] init];
    [MKTVerify(self.mockConnectionService) fetchStationSong:anything() success:[successCaptor capture] failure:[failCaptor capture]];
```

when I trying to migrate to new `HCArgumentCaptor`:
```objective-c
    HCArgumentCaptor *successCaptor = [[HCArgumentCaptor alloc] init];
    HCArgumentCaptor *failCaptor = [[HCArgumentCaptor alloc] init];
    [MKTVerify(self.mockConnectionService) fetchStationSong:anything() success:successCaptor failure:failCaptor];
```

I got this error:
```
Sending 'HCArgumentCaptor *__strong' to parameter of incompatible type 'A' (aka 'void (^)(B *__strong)')
```

My question:
is `HCArgumentCaptor` not supporting block capture? If so, what should I do it.

Thank you for your awesome project, and great articles.

**Comment by jonreid** [comment]
HCArgumentCaptor is good for capturing blocks. Try adding `(id)` casting to make the type anonymous, like

        [MKTVerify(self.mockConnectionService) fetchStationSong:anything()
                                                        success:(id)successCaptor
                                                        failure:(id)failCaptor];

**Comment by saiday** [comment]
@jonreid 
Got it, thank you for your help
