### ISSUE TITLE
Unable to @import OCMockitoIOS

### ISSUE THREAD

**Issue by jeremy-w** [jonreid/OCMockito#149]
I was surprised when I couldn't just `@import` it as a module.

It doesn't have to require clients consume it using modules, but it should support users who want to `@import OCMockitoIOS` rather than `#import <OCMockitoIOS/OCMockitoIOS.h>`.

(I suspect autolinking still won't toss in `-ObjC` for the linker, unfortunately.)

Version: OCMockito v5.0.1, OCHamcrest v7.0.2

**Comment by jonreid** [comment]
Hmm you're right. I'll start with OCHamcrest.

**Comment by jonreid** [comment]
OCHamcrest is done. OCMockito is on the way. And good news, it seems to eliminate the need for `-ObjC`

**Comment by jonreid** [comment]
Fixed in a1fc64ec, release v5.1.0
