### ISSUE TITLE
Is there a way to assert method throws?

### ISSUE THREAD

**Issue by nrudnyk** [jonreid/OCMockito#150]
would be nice to be able to do something like below:

[verify(<#methodCall#>) willThrow:<#(nonnull NSException *)#>]

does that make any sense?

**Comment by jonreid** [comment]
This can be done on an actual thrown exception with OCHamcrest:

    assertThat(^{ /* method call */ }, throwsException(hasProperty(@"reason", @"Button not found")));

I don't see how a mock object would come into the picture.
