### ISSUE TITLE
Cannot use OCMockito because of OCHamcrest.

### ISSUE THREAD

**Issue by hp1909** [jonreid/OCMockito#152]
When I compile my project using OCMockito 5.1.1 and OCHamcrest 7.1.1. It produces errors:
<img width="453" alt="Screen Shot 2019-04-25 at 4 02 30 PM" src="https://user-images.githubusercontent.com/16891742/56723636-9201c400-6773-11e9-8ec4-4e767dc2f36d.png">

**Comment by chwastek** [comment]
@hp1909  did you figure it out yet?

**Comment by hp1909** [comment]
When I removed `use_frameworks!`, I can use it.
