### ISSUE TITLE
Import OCHamcrest as a module breaks backward comptability and feels unncessary

### ISSUE THREAD

**Issue by matrush** [jonreid/OCMockito#155]
https://github.com/jonreid/OCMockito/commit/642df2bee9510bba0739af8f6924529f134bc461 changed all `#import <OCHamcrest/*.h>` to `@import OCHamcrest`, however that forces projects to enable clang modules. This is not ideal as the `#import` is backward comptabile but `@import` isn't.

I see in https://github.com/jonreid/OCMockito/commit/f26cb5864e76d60eec61dae04de9e5e61ba2de53 we reverted this once for `Foundation`, so why do we go back for `OCHamcrest` nowadays?

**Comment by jonreid** [comment]
You're right. Fixed in a9add608
