### ISSUE TITLE
Feature Request: Apple Silicon binary release

### ISSUE THREAD

**Issue by iamleeg** [jonreid/OCMockito#158]
I'm just being lazy, but it'd be good to have a release with Apple Silicon support instead of having to build from source.

**Comment by jonreid** [comment]
Graham, do I need to do add any special flags? Or just build with Xcode 12?

**Comment by jonreid** [comment]
Oh https://developer.apple.com/documentation/xcode/building_a_universal_macos_binary

**Comment by jonreid** [comment]
Let me know if these work for you:
https://github.com/jonreid/OCMockito/releases/tag/v5.1.3
https://github.com/hamcrest/OCHamcrest/releases/tag/v7.2.0

**Comment by iamleeg** [comment]
OCMockito is still x86_64 only, but OCHamcrest works great, thank you!

**Comment by jonreid** [comment]
Oh shoot, that's the current version. Try this: https://github.com/jonreid/OCMockito/releases/tag/untagged-9a1602c8dd7be7be5cf5

**Comment by jonreid** [comment]
Didn't realize people other than me couldn't see draft releases. I (quietly) published a release with the binaries, but another friend is helping me and says it doesn't work. They've opened a PR: https://github.com/jonreid/OCMockito/pull/159, something about XCFrameworks (which are new to me).

**Comment by jonreid** [comment]
Okay, switched over to XCFrameworks. Give it a try, along with the fresh-hot OCHamcrest.

**Comment by iamleeg** [comment]
Perfect, thank you!

**Comment by jonreid** [comment]
Great! I will be tweaking minor details in both releases before going official.
This was an interesting journey, I got to learn new things.
