### ISSUE TITLE
Catalyst Support for OCMockito.xcframework

### ISSUE THREAD

**Issue by janandre** [jonreid/OCMockito#161]
Hello Jon,

We have found OCMockito really helpful to mock HomeKit Data in our app.
All works great so far, except that our app supports Mac Catalyst and OCMockito not.

We get build errors, that no framework was found for it.

Is there a build setting or an easy way to get it running on mac catalyst?

Best regards,
Jan

**Comment by jonreid** [comment]
Hello @janandre. You're the first to ask for Catalyst. Let me look into it.

**Comment by jonreid** [comment]
Not yet, sorry. I need to first do the OCHamcrest release, since OCMockito depends on it.

**Comment by jonreid** [comment]
I just released the new OCHamcrest which includes Catalyst support. I'd be grateful if someone could try it and report back. Then I can proceed to OCMockito. https://github.com/hamcrest/OCHamcrest/releases/tag/v9.0.0

**Comment by jonreid** [comment]
Release is out
