### ISSUE TITLE
Assertion failure mocked NSFileManager

### ISSUE THREAD

**Issue by MBaldo83** [jonreid/OCMockito#50]
Hi,

I've been using OCMockito and OCHamcrest for a while now, and I'm very grateful for the hard work you've put into this library.

I've just installed the newest version of each, so my current OC setup is 
OCMockito 1.1.0
OCHamcrest 3.0.1

I have a problem trying to test NSFileManager, when I run the method : 
- (BOOL)fileExistsAtPath:(NSString *)path isDirectory:(BOOL *)isDirectory

I get the following assertion failure in the logs : 

*** Assertion failure in NSArray *TKArrayArgumentsForInvocation(NSInvocation *__strong)(), /Users/joreid/Development/Mockito/OCMockito/Source/OCMockito/NSInvocation+TKAdditions.m:102
Unknown.m:0: error: -[RRAudioDownloadTest testDownloadTrackSucceedsTrackIsCopiedIntoTheFileSystem] : -- Unhandled type: ^c

When I print out the instance that I'm running this method on, it looks like this : 

(lldb) po self.defaultFileManager
mock object of NSFileManager

I wonder if it's because this method is taking a BOOL * as an argument?

Expected Behaviour:

- The mocked instance of NSFileManager should not fail on assertion.

**Comment by jonreid** [comment]
I believe this was fixed as of v1.2.0, released April 5 2014.
