### ISSUE TITLE
Capturing block for further assertion throws NSException when not captured

### ISSUE THREAD

**Issue by t2wu** [jonreid/OCMockito#51]
When trying to capture block as described in capturing arguments for further assertions (https://github.com/jonreid/OCMockito), if block is not called and thus not captured, it throws in MKTCapturingMatcher line 51:
```Objective-C
@throw [NSException exceptionWithName:@"NoArgument"
                                   reason:@"No argument value was captured!\n"
                                          "You might have forgotten to use [argument capture] in verify()"
                                 userInfo:nil];
```

**Comment by jonreid** [comment]
So I should improve the exception message

**Comment by jonreid** [comment]
This seems correct to me. If it surprises you, please explain what you would expect instead.
