### ISSUE TITLE
Need to be able to mock sequential returns

### ISSUE THREAD

**Issue by dcorbin** [jonreid/OCMockito#68]
I have a method that takes no arguments, and returns something (potentially) different with  each call.  willReturn: seems to only return the last thing the mock was configured with for each call. I even tried chaining willReturn method calls (similar to what Mockito does here: http://2min2code.com/articles/mockito_intro/stubbing_method_sequential)  to no effect.

**Comment by jonreid** [comment]
And you shall have it. 36680ec

**Comment by jonreid** [comment]
Would you also be interested in a shorthand method, so you didn't have to do all the chaining? Like

    [given([mockObject someMethod]) willReturnObjects:@[@"foo", @"bar", @"baz"]];

**Comment by jonreid** [comment]
On second thought, let's not do the shorthand, at least not yet.

**Comment by dcorbin** [comment]
I think the situation is uncommon enough that the short hand method is not worth it anyway.
