### ISSUE TITLE
verify() does not work with methods that have NSError** as parameter

### ISSUE THREAD

**Issue by renep** [jonreid/OCMockito#77]
For my API operation tests I mock the actual http request. For this I have put all my http code into an own server request class that I can replace in the operation.

It looks like this:

```
@interface MyServerRequest : NSObject
- (id)sendRequestWithParameters:(NSDictionary *)parameters error:(NSError **)error;
@end
```

Now I have a unit test that tests the operation if the correct parameters are passed:
```
MyServerRequest *serverRequest = mock([MyServerRequest class]);

MyOperation *operation = [MyOperation operation] initWithServerRequest:serverRequest]
[operation main]; // in the main the sendRequestWithParameters is called

MKTArgumentCaptor *requestParameterArgument = [[MKTArgumentCaptor alloc] init];
[verify(serverRequest) sendRequestWithParameters:[requestParameterArgument capture] error:nil];

```

The problem here is that the verify does not work, because the error parameter cannot be ignored will nil or anything()

My solution so far is to remove the MKTPointerArgumentGetter from the MKTArgumentGetterChain, then the error parameter can be ignored, and all my test are working fine.

My opinion is that if NSObject** parameters cannot be captured, than they should be ignored (like this was the case in the previous versions of OCMockito)

**Comment by jonreid** [comment]
I see, you want a way to say, "Don't match this argument."

**Comment by renep** [comment]
Yes

**Comment by jonreid** [comment]
I went to add the mechanism, only to discover it was already there (but needs to be shown in the README). This should work:

```obj-c
[verify(serverRequest) withMatcher:anything() forArgument:1]
 sendRequestWithParameters:[requestParameterArgument capture] error:nil];
```

**Comment by anandrahul** [comment]
@jonreid I would appriciate if you could put this case somewhere in the documentation. I have wasted hours trying to make such a similar case and did not manage to fix until accidentally found this answer.
