### ISSUE TITLE
Xcode6: warning when verifying setDelegate: method call

### ISSUE THREAD

**Issue by garnett** [jonreid/OCMockito#81]
In Xcode6 the following code  
   ```objective-c
    id <Foo> foo = mockProtocol(@protocol(Foo));
    id <Bar>delegate =  mockProtocol(@protocol(Bar));
    [MKTVerify(foo) setDelegate:delegate];
```

produces warning
```Sending '__strong id<Bar>' to parameter of incompatible type 'id<NSFileManagerDelegate>'```

I've example project can be found [here]( https://github.com/garnett/TestProjects/tree/ocmockito-warning)

**Comment by jonreid** [comment]
Your casting to `typeof(mock)` fixes that warning, but creates other problems because sometimes you need to call `-withMatcher:forArgument:` — which of course is defined on the mock, but not on the actual object.

I think the workaround is to do the casting directly in the test code.
