### ISSUE TITLE
cannot verify invocation of reset method

### ISSUE THREAD

**Issue by thenewrohirrim** [jonreid/OCMockito#85]
Hi,

Thank you for a terrific piece of software.

The following passes but shouldn't:

- (void) testFoo {
    NSString *string = mock([NSString class]);
    [verify(string) reset];
}

The reason it passes is that even though verify puts the mock in verification mode, the reset method that the MKTBaseMockObject offers.

Took me a while to figure out why my tests were passing even though I hadn't written the code under test :-)

Thanks

**Comment by tomaszbak** [comment]
+ 1 I'm facing same issue

**Comment by jonreid** [comment]
Renamed to `mkt_resetMock`
