### ISSUE TITLE
Testing Core Data relationship

### ISSUE THREAD

**Issue by kiennt** [jonreid/OCMockito#88]
I have Core data models like this

```obj-c

@interface Book: NSManagedObject
- (NSString *)coverURL;
@end

@interface Order: NSManagedObject 
@property(nonatomic, strong) Book *book
@property(nonatomic, strong) NSString *previewURL;
- (NSURL *)imageURL;
@end

@implement Order 

- (NSString *)imageURL {
    if (!self.previewURL) {
        self.previewURL = [self.book coverURL];
    }
    return self.previewURL;
}

@end

```

I test `imageURL` function like this (I using Specta and Expecta)

```objc
__block Order *order;

beforeAll(^{
    [MagicalRecord setupCoreDataStackWithInMemoryStore];
    order = [Order createOrder]; // code to create order
});

afterAll(^{
    [MagicalRecord cleanUp];
});

describe(@"Order", ^{
    it(@"should call book coverURL if previewURL is not set", ^{
        Book *book = mock([Book class]);
        order.book = book;
        [order imageURL];
        [verifyCount(book, times(1)) randomPostURL];
    });
});
```

The thing is book is mock object, so I could not set order.book to book. 
How do we write test in this case?

**Comment by jonreid** [comment]
-[FooTests testExample] : failed: caught "NSInvalidArgumentException", "Unacceptable type of value for to-one relationship: property = "book"; desired type = Book; given type = MKTObjectMock; value = mock object of Book."

So an OCMockito-created mock won't work. You may have better luck with OCMock, which creates mocks as subclasses.

But the deeper solution would be to separate your data storage (Core Data) from your business logic. Check out http://qualitycoding.org, where I will soon be posting a series on iOS architecture.

**Comment by kiennt** [comment]
@jonreid 

Thanks for explaination.

Currently in our app, I put most of my logic in model (which is CoreData). I came from Python world in which that architecture is fine, but in ObjC and CoreData, it 's seem not a right solution. 

I am looking forward to read new article in your blog
