### ISSUE TITLE
Stubbing of NSUserDefaults apparently doesn't work

### ISSUE THREAD

**Issue by lumaxis** [jonreid/OCMockito#92]
In one of my Unit Tests I do the following:
```objectivec
  [given([mockUserDefaults boolForKey:@"key"]) willReturnBool:YES];
  assertThatBool([mockUserDefaults boolForKey:@"key"], equalToBool(YES));
```
But for some reason the stubbing of `boolForKey` doesn't work. Similar stubs with e.g. `valueForKey` work perfectly fine. Might this be an issue with OCMockito or am I doing something wrong?
Thanks a lot!

**Comment by manumax** [comment]
Probably you have already solved, but it works fine for me:
```
    NSUserDefaults *mockUserDefaults = mock([NSUserDefaults class]);    
    [given([mockUserDefaults boolForKey:@"key"]) willReturnBool:YES];    
    assertThatBool([mockUserDefaults boolForKey:@"key"], equalToBool(YES));
```

**Comment by malaimoo** [comment]
how about [NSUserDefaults standardUserDefaults] ? how can I mock a singleton like [NSUserDefaults standardUserDefaults] ？

**Comment by jonreid** [comment]
@malaimoo The OCMock way is through method swizzling.
The OCMockito way is to make your dependencies explicit. Inject the NSUserDefaults singleton through any of the Dependency Injection styles:

- Constructor Injection (pass as initializer argument)
- Property Injection (defaults to singleton, but can be replaced)
- Method Injection (pass as method argument)
- Ambient Context (either a Service Locator, or your own swizzling)

Note that when it's passed as an argument to either the initializer or to a specific method, you can add a second layer to make it implicit. For example, use Constructor Injection where the designated initializer requires a NSUserDefaults  instance. But then make a second initializer that calls it, passing in `[NSUserDefaults standardUserDefaults]`.
