### ISSUE TITLE
Generate KVO from Mocked Objects

### ISSUE THREAD

**Issue by ronak2121** [jonreid/OCMockito#96]
Hi,

We are trying to unit test methods on a class that is registered for KVO on an object that we are mocking. Using stubProperty doesn't actually seem to help force the mocked object to generate KVO on its own. Calling willChange/didChange standard KVO methods doesn't do anything either (since we're calling methods on a mock object). How do you actually unit test your KVO handlers?

Our fallback option forces us to expose those KVO methods in the public header, which makes us break encapsulation and proper method visibility.

Thanks,

Ronak Patel

**Comment by bssayeda** [comment]
+1

**Comment by rparvathaneni** [comment]
+1

**Comment by manumax** [comment]
What if you call directly the method KVO would call passing the expected properties? Something like:

```
 [listener observeValueForKeyPath:@"someProperty"
                         ofObject:emitter
                           change:@{NSKeyValueChangeKindKey: @(1),
                                     NSKeyValueChangeOldKey: @(0)}
                          context:nil];

```
where `listener` is the object registered for KVO and `emitter` is your mock.
Shouldn't be enough or I'm missing something?

**Comment by ronak2121** [comment]
We use Facebook's KVO Controller actually...and I have found a way...inject a mock to replace Facebook, capture the blocks and call those blocks on my own to test.
