### ISSUE TITLE
Verify method name clashe

### ISSUE THREAD

**Issue by emartynov** [jonreid/OCMockito#97]
I have class with ```@property ... value```. However when I write next verify:
```
[verify(mockedFieldView) setValue:value];
```
I got compilation error with error saying ```Error:(104, 5) multiple methods named 'setValue:' found with mismatched result, parameter type or attributes```

Please assist me

**Comment by emartynov** [comment]
I found the solution. Sorry for bothering.

For anyone interested:
```
[(FieldView*)verify(mockedFieldView) setValue:value];
```

**Comment by jonreid** [comment]
Yup, that's it.
