### ISSUE TITLE
Using given to mock methods with multiple arguments

### ISSUE THREAD

**Issue by andrewjl** [jonreid/OCMockito#99]
When I try the below, it works great:
```
[given([mockAPIManager initWithBaseURL:[mockAPIManager baseURL]]) willReturn:[DSAPIManager sharedAPIManager]];
```
However when I try the same thing on a method with multiple arguments (see code below), I get an `"Argument type 'void' is incomplete'`  compiler error.
```
[given([mockAPIManager setLoginCredentialsWithEmail:@""
                                           password:@""]) willReturn:@""];
```
Does anyone know the right way to go about this?

**Comment by jonreid** [comment]
https://github.com/jonreid/OCMockito/pull/93
